- name: Ensure docker-compose.yaml is present
  copy:
    src: "{{ playbook_dir }}/../docker-compose.yaml"
    dest: /home/debian/docker-compose.yaml
    mode: '0644'

- name: Copiar fonte de dados do Grafana (Prometheus)
  copy:
    src: "{{ playbook_dir }}/../provisioning"
    dest: /home/debian/provisioning
    mode: '0755'
    directory_mode: '0755'

- name: Start Grafana container
  command: docker-compose -f /home/debian/docker-compose.yaml up -d grafana
