global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'gce'
    gce_sd_configs:
      - project: app-chamada-5706
        zone: us-central1-a
        port: 9100
    relabel_configs:
      - source_labels: [__meta_gce_instance_name]
        target_label: instance
  - job_name: 'local-node'
    static_configs:
      - targets: ['node-exporter:9100']

