name: Create Cluster Name and Save as Org Secret

on:
  push:
    branches: [dev]
  workflow_dispatch:

env:
  ORG_NAME: o-grupo-x
  SECRET_NAME: GKE_CLUSTER_NAME

jobs:
  create-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set Short Commit SHA
        id: vars
        run: echo "short_sha=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

      - name: Upload Secret to Organization
        uses: cschleiden/gh-action-create-org-secret@v1
        with:
          secret-name: ${{ env.SECRET_NAME }}
          secret-value: app-prod-${{ steps.vars.outputs.short_sha }}
          organization: ${{ env.ORG_NAME }}
          token: ${{ secrets.PAT_GITHUB }}
