name: Build and Deploy

on:
  push:
    branches: [main, dev, gui]
  pull_request:
    branches: [main, dev, gui]

env:
  PROJECT_ID: app-chamada-5706

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS_B64 }}
          export_default_credentials: true
      - name: Configure Docker
        run: gcloud auth configure-docker -q
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4
      - name: Restore credentials.json
        run: echo "${{ secrets.GCP_CREDENTIALS_B64 }}" | base64 -d > terraform/credentials.json
      - name: Terraform Init
        run: terraform init
        working-directory: terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform
      - name: Export cluster info
        run: |
          echo "CLUSTER_NAME=$(terraform output -raw cluster_name)" >> $GITHUB_ENV
          echo "CLUSTER_ZONE=$(terraform output -raw cluster_zone)" >> $GITHUB_ENV
        working-directory: terraform
      - name: Build image
        run: |
          docker build -t gcr.io/${{ env.PROJECT_ID }}/frontend:${{ github.sha }} .
      - name: Push image
        run: |
          docker push gcr.io/${{ env.PROJECT_ID }}/frontend:${{ github.sha }}
      - name: Get cluster credentials
        run: |
          gcloud container clusters get-credentials "$CLUSTER_NAME" --zone "$CLUSTER_ZONE" --project "$PROJECT_ID"
      - name: Deploy
        run: |
          kubectl apply -f k8s/
          kubectl set image deployment/frontend frontend=gcr.io/${{ env.PROJECT_ID }}/frontend:${{ github.sha }}
