name: Create Cluster Name and Save as Org Variable

on:
  push:
    branches: [dev]
  workflow_dispatch:

env:
  ORG_NAME: o-grupo-x
  VAR_NAME: GKE_CLUSTER_NAME

jobs:
  create-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set Short Commit SHA
        id: vars
        run: echo "short_sha=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

      - name: Create Cluster Name
        id: cluster
        run: echo "cluster_name=app-prod-${{ steps.vars.outputs.short_sha }}" >> $GITHUB_OUTPUT

      - name: Upload Organization Variable
        run: |
          CLUSTER_NAME="app-prod-${{ steps.vars.outputs.short_sha }}"
          curl -X PATCH \
            -H "Authorization: Bearer ${{ secrets.PAT_GITHUB }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/orgs/${{ env.ORG_NAME }}/actions/variables/${{ env.VAR_NAME }} \
            -d "{\"name\":\"${{ env.VAR_NAME }}\", \"value\":\"$CLUSTER_NAME\"}" \
          || curl -X POST \
            -H "Authorization: Bearer ${{ secrets.PAT_GITHUB }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/orgs/${{ env.ORG_NAME }}/actions/variables \
            -d "{\"name\":\"${{ env.VAR_NAME }}\", \"value\":\"$CLUSTER_NAME\"}"
