name: Terraform Plan & Deploy Pipeline
on:
  push:
    branches: [main, gui]
  pull_request:
    branches: [main, gui]
jobs:
  terraform-and-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4

      - name: Restaurar credentials.json
        run: |
          echo "${{ secrets.GCP_CREDENTIALS_B64 }}" | base64 -d > ./terraform/credentials.json

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan ou Apply
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ] || [ "${{ github.ref }}" = "refs/heads/gui" ]; then
            terraform apply -auto-approve -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"
          else
            terraform plan -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"
          fi
        working-directory: ./terraform

      - name: Instalar Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/gui'

      - name: Configurar SSH para Ansible
        run: |
          # Ensure ansible directory exists
          mkdir -p ./ansible
          # Write the SSH private key from secret directly
          echo "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}" > ./ansible/ssh_key
          chmod 600 ./ansible/ssh_key
        working-directory: ./ansible
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/gui'

      - name: Atualizar inventory com IP da VM
        run: |
          VM_IP=$(terraform output -raw instance_ip)
          echo "[vm]\n$VM_IP ansible_user=debian ansible_ssh_private_key_file=./ansible/ssh_key" > ./ansible/hosts.ini
        working-directory: ./terraform
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/gui'

      - name: Executar Ansible Playbook
        run: |
          ansible-playbook -i hosts.ini playbook.yaml
        working-directory: ./ansible
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/gui'
